### ISSUE TITLE
What happened to definePrim?

### ISSUE THREAD

**Issue by sholladay** [requirejs/alameda-prim#2]
As the author of a third-party JavaScript application, it would be irresponsible of me to define `window.Promise` on my customer's pages with a polyfill meant for my own use.

The `definePrim` feature from before `alameda` and `alameda-prim` split apart was very useful to me, to keep the polyfill completely private.

**Comment by jrburke** [comment]
I wasn't sure if it was used, and with alameda going with native promises, I just thought it was simpler to just have this alameda+private promise shim.

However, I am not opposed to adding definePrim back to this project. If you are interested in seeing it in, I am open to seeing a pull request for it. Probably extending build-alameda-prim.js to inject a config check for definePrim and do the work, probably in the config method, maybe before this call:

https://github.com/requirejs/alameda-prim/blob/master/parts/alameda.js#L1172

since it should be done before the config does a require for any config.deps.

**Comment by sholladay** [comment]
Closing as I probably won't get around to this anytime soon. And by then, who knows where native ES modules will be, etc.
